Fix compilation error.
With `-Werror` gcc-14.1.1 (with libstdc++-14) emits an error:
`error: ignoring return value of _FIter std::remove_if(_FIter, _FIter, _Predicate)
... ...
declared with attribute nodiscard [-Werror=unused-result]`.
Use cast to `void` to avoid it.