Add missing header.
When I have tried to build yarpgen on ArchLinux
the build failed with
"/home/dima/work/yarpgen/src/options.h:122:5: error: ‘uint64_t’ does not name a type
  122 |     uint64_t getSeed() { return seed; }
      |     ^~~~~~~~
/home/dima/work/yarpgen/src/options.h:28:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’;..."